version: '3.4'

x-app-service-template: &app
  build: rails_app
  image: yabeda-rails-app:1.0
  volumes:
    - ./rails_app:/app

services:
  rails:
    <<: *app
    ports:
      - 5000:5000
    environment:
      REDIS_URL: redis://redis:6379/0
    stdin_open: true
    tty: true
    depends_on:
      - redis

    command: bundle exec puma -C config/puma.rb

  sidekiq:
    <<: *app
    ports:
      - 5100:5100
    environment:
      PORT: 5100
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

    command: sidekiq -C config/sidekiq.yml

  redis:
    image: redis
    command: redis-server
    ports:
      - 6379:6379/tcp

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus    
    ports:
      - 3000:3000/tcp
    volumes: 
      - ./grafana_db:/var/lib/grafana
    user: "0"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    ports:
      - 9090:9090/tcp
    depends_on:
      - rails
    user: root

    command:
      - --config.file=/etc/prometheus/prometheus.yml

  rails_stressor:
    build: rails_stressor
    image: rails_stressor
    depends_on:
      - rails
    command: -z 20m -c 150 -m GET http://rails:5000

  redis-exporter:
      image: oliver006/redis_exporter
      command: -redis.addr redis://redis:6379
      ports:
      - 9121:9121

  elasticsearch_exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    command:
     - '--es.uri=https://elastic:23LAqK8Y1QpGZDjsnFZxBGnl@initial-dep.es.ap-northeast-2.aws.elastic-cloud.com/'
    restart: always
    ports:
    - 9114:9114


#grafana dachboards 14091 redis 

