global:
  scrape_interval: 15s
  evaluation_interval: 15s
remote_write:
- url: https://metric-api.newrelic.com/prometheus/v1/write?prometheus_server=demo-prom-test-source
  bearer_token: 082dda0ab502455631374641ee8969422801NRAL
  
scrape_configs:
- job_name: 'rails'
  scheme: http
  metrics_path: '/metrics'
  static_configs:
    - targets:
      - 'rails:5000'
- job_name: 'sidekiq'
  scheme: http
  metrics_path: '/metrics'
  static_configs:
    - targets:
      - 'sidekiq:5100'
